# Generated by Django 5.2.1 on 2025-05-23 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_carrito_itemscarrito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes_pago/')),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('carrito_original', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_asociada', to='libreria.carrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
